stages:
  - build
  - deploy

doorstop:
  stage: build
  image: ubuntu:bionic
  script:
    - 'apt-get update && apt-get -y --no-install-recommends install
          git
	  python3-pip
	  ca-certificates
      '
    # update pip
    - python3 -m pip install pip --upgrade
    # install latest doorstop
    - git clone https://github.com/doorstop-dev/doorstop.git
    - 'cd doorstop && pip3 install .'
    - 'cd .. && rm -rf doorstop'
    # run doorstop
    - 'doorstop &> doorstop.log'
    - '! grep "WARNING:" doorstop.log'
    - '! grep "ERROR:" doorstop.log'
    # publish requirements
    - doorstop publish all ./docs
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - doorstop.log
      - docs

pages:
  stage: deploy
  image: alpine
  dependencies:
    - doorstop
  script:
    - mv docs public
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - public
